# Generated by Django 3.2.19 on 2025-03-11 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_capacity_allowed_in_kgs', models.PositiveIntegerField(default=0)),
                ('number_of_cartons', models.PositiveIntegerField(default=0)),
                ('is_special_case', models.BooleanField(default=False)),
                ('max_packages', models.PositiveIntegerField(default=3)),
                ('lod_offload', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('LOOSE', 'LOOSE'), ('CARTON', 'CARTON')], max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packaging.line')),
            ],
        ),
        migrations.CreateModel(
            name='QualityMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_product', models.CharField(max_length=100, unique=True)),
                ('mass_of_product', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('weight_capacity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_allowed_capacity_in_kgs', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('capacity_limit_number', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packaging.package')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packaging.rack')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packaging.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='quality_mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packaging.qualitymark'),
        ),
        migrations.AddField(
            model_name='line',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packaging.warehouse'),
        ),
    ]
