# Generated by Django 4.2.1 on 2025-03-11 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pallet',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='rack',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='packaging.warehouse'),
            preserve_default=False,
        ),
    ]
