# Generated by Django 4.2.1 on 2025-03-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0002_remove_pallet_warehouse_rack_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='current_available_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='current_available_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
