# Generated by Django 4.2.1 on 2025-03-11 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0003_rack_current_available_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pallet',
            name='package',
        ),
        migrations.AddField(
            model_name='package',
            name='pallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packaging.pallet'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='current_available_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packaging.line'),
        ),
    ]
