# Generated by Django 4.2.1 on 2025-03-11 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0004_remove_pallet_package_package_pallet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='lod_offload',
        ),
    ]
