# Generated by Django 4.2.1 on 2025-03-12 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0005_remove_line_lod_offload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='quality_mark',
        ),
        migrations.AddField(
            model_name='line',
            name='current_available_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='line',
            name='name',
            field=models.CharField(default='packt', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='mass_of_product',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.CharField(default='packd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='type_of_product',
            field=models.CharField(default='packs', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='line',
            name='max_packages',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.DeleteModel(
            name='QualityMark',
        ),
    ]
