# Generated by Django 4.2.1 on 2025-03-12 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0006_remove_package_quality_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_pallet', to='packaging.rack'),
        ),
    ]
