# Generated by Django 5.1.6 on 2025-02-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_date_of_birth_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='spousedetail',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='nextofkin',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='personalidentification',
            name='customer',
        ),
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_branch_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='AdditionalService',
        ),
        migrations.DeleteModel(
            name='SpouseDetail',
        ),
        migrations.DeleteModel(
            name='NextOfKin',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='PersonalIdentification',
        ),
    ]
