# Generated by Django 5.1.6 on 2025-02-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_customer_user_remove_spousedetail_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_operations',
            field=models.BooleanField(default=False),
        ),
    ]
