# Generated by Django 5.1.7 on 2025-03-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_is_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agent',
            new_name='Operator',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_agent',
            new_name='is_system_operator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_operations',
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
