# Generated by Django 3.2.19 on 2025-03-11 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_agent_operator_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
