# Generated by Django 4.2.1 on 2025-03-11 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_branch_manager',
            new_name='is_logistics_manager',
        ),
    ]
