# Generated by Django 4.2.1 on 2025-03-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_is_branch_manager_user_is_logistics_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BranchManager',
            new_name='LogisticsManager',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_system_operator',
            field=models.BooleanField(default=True),
        ),
    ]
